apiVersion: v1
description: MLRUn Open Source Stack
home: https://iguazio.com
icon: https://www.iguazio.com/wp-content/uploads/2019/10/Iguazio-Logo.png
maintainers:
- email: adamm@iguazio.com
  name: Adam Melnick
- email: eliyahun@iguazio.com
  name: Eliyahu Noach
name: mlrun-ce
version: 0.6.2
