project_name: cicd-flow
local_source: 'v3io:///bigdata/cicd-flow.zip'
git_source: 'git://github.com/igz-us-sales/igz-cicd-flow#master'
allow_validation_failure: true
label_column: target
ohe_columns:
- sex
- cp
- slope
- thal
- restecg
source_url: ./data/heart.csv
test_size: 0.1
model_name: model
model_path: 'store://models/cicd-flow/model#4:4c054e48-2d96-4cd8-8494-7855594c816b'
train_set: 'store://datasets/cicd-flow/data-process-data_train#0:4c054e48-2d96-4cd8-8494-7855594c816b'
test_set: 'store://datasets/cicd-flow/data-process-data_test#0:4c054e48-2d96-4cd8-8494-7855594c816b'