kind: project
metadata:
  name: cicd-flow
  created: '2024-09-27T19:26:50.786000'
spec:
  params:
    source: v3io:///bigdata/cicd-flow.zip
    secrets_file: secrets.env
    artifact_path: s3://iguazio-demo/projects/{{run.project}}/artifacts
    force_build: false
    user_project: false
  functions:
  - url: src/functions/data.py
    name: data
    kind: job
    with_repo: true
  - url: hub://describe
    name: describe
    kind: job
    handler: analyze
  - url: src/functions/train.py
    name: train
    kind: job
    image: mlrun/mlrun:1.6.2
    handler: train_model
  - url: src/functions/validate.py
    name: validate
    kind: job
  - url: src/functions/test_classifier.py
    name: test
    kind: job
    handler: test_classifier
  - url: hub://v2_model_server
    name: serving
    kind: serving
    image: mlrun/mlrun:1.6.2
    requirements_file: requirements.txt
  - url: hub://v2_model_tester
    name: model-server-tester
    kind: job
    handler: model_server_tester
  - url: src/functions/get_model_uri.py
    name: get-model-uri
    kind: job
    handler: get_model_uri_from_tag
  workflows:
  - path: src/workflows/train_workflow.py
    name: train
  - path: src/workflows/deploy_workflow.py
    name: deploy
  artifacts:
  - import_from: artifacts/model:challenger.yaml
    key: model
    tag: challenger
  artifact_path: s3://iguazio-demo/projects/{{run.project}}/artifacts
  conda: ''
  source: v3io:///bigdata/cicd-flow.zip
  origin_url: git://github.com/igz-us-sales/igz-cicd-flow.git#refs/heads/development
  load_source_on_run: true
  desired_state: online
  owner: nick
  default_image: .mlrun-project-image-cicd-flow
  build:
    image: .mlrun-project-image-cicd-flow
    base_image: mlrun/mlrun:1.6.2
    commands:
    - pip install PyGithub==1.59.0 deepchecks==0.18.1 pandera==0.20.3
    with_mlrun: false
    requirements: []
  custom_packagers: []
status:
  state: online
