#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: b4bz/homer
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    type: NodePort
    ports:
      http:
        port: 8080
        nodePort: 30000


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

securityContext:
  # -- Specify the user ID the application will run as
  runAsUser: 1000
  # -- Enable validation that the container must run as non-root user
  runAsNonRoot: true
  # -- Specify the group ID the application will run as
  runAsGroup: 1000

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /www/assets

configmap:
  config:
    # -- Store homer configuration as a ConfigMap
    enabled: true
    # -- Homer configuration. See [image documentation](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md) for more information.
    # @default -- See values.yaml
    data:
      config.yml: |
        ---
        # Homepage configuration
        # See https://fontawesome.com/icons for icons options

        title: "MLOps Workbench Dashboard"
        # subtitle: "Homer"
        # logo: "logo.png"
        icon: "fas fa-computer" # Optional icon

        columns: "3"

        header: true
        footer: false

        defaults:
          layout: list
          colorTheme: dark

        # Optional theme customization
        theme: default
        colors:
          light:
            highlight-primary: "#3367d6"
            highlight-secondary: "#4285f4"
            highlight-hover: "#5a95f5"
            background: "#f5f5f5"
            card-background: "#ffffff"
            text: "#363636"
            text-header: "#ffffff"
            text-title: "#303030"
            text-subtitle: "#424242"
            card-shadow: rgba(0, 0, 0, 0.1)
            link-hover: "#363636"
          dark:
            highlight-primary: "#3367d6"
            highlight-secondary: "#4285f4"
            highlight-hover: "#5a95f5"
            background: "#131313"
            card-background: "#2b2b2b"
            text: "#eaeaea"
            text-header: "#ffffff"
            text-title: "#fafafa"
            text-subtitle: "#f5f5f5"
            card-shadow: rgba(0, 0, 0, 0.4)
            link-hover: "#ffdd57"

        # Optional message
        #message:
        #  #url: https://b4bz.io
        #  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
        #  title: "Demo !"
        #  icon: "fa fa-grin"
        #  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

        # Optional navbar
        # links: [] # Allows for navbar (dark mode, layout, and search) without any links
        #
        #links:
        #  - name: "Contribute"
        #    icon: "fab fa-github"
        #    url: "https://github.com/bastienwirtz/homer"
        #    target: "_blank" # optional html a tag target attribute
        #  - name: "Wiki"
        #    icon: "fas fa-book"
        #    url: "https://www.wikipedia.org/"
        #  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
        #  # see url field and assets/additionnal-page.yml.dist used in this example:
        #  - name: "another page!"
        #    icon: "fas fa-file-alt"
        #    url: "#additionnal-page" 

        # Services
        # First level array represent a group.
        # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
        
        services:
          - name: "Compute"
            icon: "fas fa-cloud"
            items:
              - name: "Jupyter Notebook"
                subtitle: "Notebook Servers"
                url: "http://localhost:30040"
                logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/414px-Jupyter_logo.svg.png"
                target: "#"
              - name: "MLRun UI"
                subtitle: "MLOps Workbench"
                url: "http://localhost:30060"
                logo: "https://www.mlrun.org/hub/images/functions/mlrun.png"
                target: "#"
              - name: "Nuclio"
                subtitle: "Real-Time Serverless Functions"
                url: "http://localhost:30050"
                logo: "https://nuclio.wpenginepowered.com/wp-content/uploads/2017/10/superman.png"
                target: "#"
              - name: "Kubeflow Pipelines"
                subtitle: "Pipeline orchestration"
                url: "http://localhost:30100"
                target: "#"
                logo: "https://avatars.githubusercontent.com/u/33164907?s=200&v=4"

          - name: "API"
            icon: "fas fa-cloud"
            items:
              - name: "MLRun API"
                subtitle: "MLOps API"
                url: "http://localhost:30070"
                target: "#"
                logo: "https://www.mlrun.org/hub/images/functions/mlrun.png"
              - name: "Spaceflights API"
                subtitle: "API for Spaceflights"
                url: "http://localhost:30098"
                target: "#"
                logo: "https://creazilla-store.fra1.digitaloceanspaces.com/emojis/47653/rocket-emoji-clipart-xl.png"

          - name: "Monitoring"
            icon: "fas fa-cloud"
            items:
              - name: "Grafana"
                logo: "https://static-00.iconduck.com/assets.00/grafana-icon-512x512-0v0st1xm.png"
                subtitle: "Dashboards and Alerting"
                url: "http://localhost:30110"
                target: "#"
              - name: "Prometheus"
                subtitle: "Metrics Collection"
                url: "http://localhost:30120"
                target: "#"
                logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/2066px-Prometheus_software_logo.svg.png"

          - name: "Storage"
            icon: "fas fa-cloud"
            items:
              - name: "Minio"
                subtitle: "Object Storage"
                url: "http://localhost:30090"
                target: "#"
                logo: "https://min.io/resources/img/logo/MINIO_Bird.png"
              - name: "Spaceflights Minio"
                subtitle: "Object Storage for Spaceflights"
                url: "http://localhost:30099"
                target: "#"
                logo: "https://min.io/resources/img/logo/MINIO_Bird.png"