apiVersion: v1
appVersion: 1.4.0
description: Machine Learning automation and tracking
icon: https://di5r923elu32w2e633ofbxj9-wpengine.netdna-ssl.com/wp-content/uploads/2019/10/Iguazio-Logo.png
maintainers:
- email: hedii@iguazio.com
  name: hedingber
name: mlrun
sources:
- https://github.com/mlrun/mlrun
version: 0.9.14
