apiVersion: v1
appVersion: "1.0"
description: V3IO configuration templates
icon: https://www.iguazio.com/wp-content/uploads/2019/10/Iguazio-Logo.png
maintainers:
- email: eliranb@iguazio.com
  name: bivas
name: v3io-configs
sources:
- https://github.com/iguazio/kubeops/
version: 0.11.3
