name: CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    container:
      image: mlrun/mlrun:1.6.2
      
    steps:
    - uses: actions/checkout@v2
    - name: Install make
      run: apt-get update && apt-get install make -y
    - name: Install dependencies
      run: make install-requirements
    - name: Lint
      run: make lint
      
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    container:
      image: mlrun/mlrun:1.5.0
      
    steps:
    - uses: actions/checkout@v2
    - name: Install make
      run: apt-get update && apt-get install make -y
    - name: Install dependencies
      run: make install-requirements
    - name: Unit tests
      run: make test
