name: Deploy Workflow
on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - staging
      - master

jobs:
  deploy-workflow:
    name: deploy-model
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    container:
      image: mlrun/mlrun:1.4.1
      options: --user 1001
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Current Branch
      id: branch
      run: echo "branch=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_OUTPUT
    - name: Deploy model
      run: |
        python main.py --workflow-name deploy --source git --branch ${{ steps.branch.outputs.branch }} --single-cluster-mode
      env:
        V3IO_USERNAME: ${{ secrets.V3IO_USERNAME }}
        V3IO_PASSWORD: ${{ secrets.V3IO_USERNAME }}
        V3IO_API: ${{ secrets.V3IO_API }}
        V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
        MLRUN_DBPATH: ${{ secrets.MLRUN_DBPATH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        CMD: ${{ github.event.comment.body}}  
        COMMIT: ${{ github.sha}}
